#pragma config(Sensor, in1,    motor1_angle,    sensorPotentiometer)
#pragma config(Sensor, in2,    motor2_angle,    sensorPotentiometer)
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//MAX_SENSOR, used as a comparitively LOW sensor value when beaming for beacon.
int MAX_SENSOR = 0;

//unload: deposits object on top of beacon.
void unload () {

}

//drive: drives in a straight line.
void drive () {

}

//stop: stops all motors.
void stop () {

}

//detect: spins the robot in a circle, returns true when robot is pointing towards beacon.
bool detect () {

}

void beam () {

}

task main () {
	
    enum robotState {
		STOP = 0,
        MOVING = 1,
		ON_TARGET = 2,
		OFF_TARGET = 3,
	};

	robotState state = MOTOR_STOP;

    while (1) {
        switch (state) {
            case STOP:
                break;
            case MOVING:
                break;
            case ON_TARGET:
                drive();
                break;
            case OFF_TARGET:
                stop();
                break;
        }
    }
}
